import localFont from "next/font/local";
import "./globals.css";
import Header from "./component/Header/Header";
import SessionProvider from "../../utils/SessionProvider";
import { getServerSession } from "next-auth";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
        <div className="">
        <Header />        
        {children}
        </div>
        </SessionProvider>
      </body>
    </html>
  );
}
